// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://twqyktxnqjkzahpwxpyo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR3cXlrdHhucWpremFocHd4cHlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE1MzQ1OTgsImV4cCI6MjA1NzExMDU5OH0.P4bAYpbJ_vgpR7YpUItdKtS_FTsRqXZ9WllVuZQw8iY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);